# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'onecleaner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""One cleaner by m133"""

from os import system,path
from tempfile import gettempdir
from PyQt5 import QtCore, QtGui, QtWidgets
from sys import argv,exit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(803, 491)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(250, 20, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.header.setFont(font)
        self.header.setStyleSheet("background:rgba(255, 255, 255, 0)")
        self.header.setObjectName("header")
        self.by = QtWidgets.QLabel(self.centralwidget)
        self.by.setGeometry(QtCore.QRect(0, 470, 47, 13))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        self.by.setFont(font)
        self.by.setStyleSheet("    background: #FFF;")
        self.by.setObjectName("by")
        self.cleanBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cleanBtn.setGeometry(QtCore.QRect(260, 170, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(28)
        self.cleanBtn.setFont(font)
        self.cleanBtn.setStyleSheet("background: #FFF;")
        self.cleanBtn.setObjectName("cleanBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(760, 460, 51, 20))
        self.label.setStyleSheet("background: #FFF;")
        self.label.setObjectName("label")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(750, 10, 41, 41))
        self.closeBtn.setText('X')
        self.closeBtn.setStyleSheet("background: #F00;")
        font.setPointSize(18)
        self.closeBtn.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.addFunctions()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "oneCleaner"))
        self.header.setText(_translate("MainWindow", "oneCleaner"))
        self.by.setText(_translate("MainWindow", "by m133"))
        self.cleanBtn.setText(_translate("MainWindow", "Почистить!"))
        self.label.setText(_translate("MainWindow", "v1.0"))
    def addFunctions(self):
        self.closeBtn.clicked.connect(QtWidgets.qApp.quit)  
        self.cleanBtn.clicked.connect(self.cleaner) 
    def cleaner(self):
        system("rmdir %temp% /s /q ")
        if path.isfile(gettempdir()):
            system("mkdir %temp%")
        self.cleanBtn.setStyleSheet("background:#0f0;")
if __name__ == "__main__":
    app = QtWidgets.QApplication(argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    exit(app.exec_())